spring:
  application:
    name: api-gateway
  cloud:
    loadbalancer:
      rule: random
    gateway:
      routes:
        - id: product_service
          uri: http://localhost:8081
          predicates:
            - Path=/product_service/**
          ##uri: lb//PRODUCT-SERVICE
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/order-service/**
        - id: Employee-service
          uri: http://localhost:8083
          predicates:
            - Path=/Employee-service/**
        - id: inventory-service
          uri: http://localhost:3000
          predicates:
            - Path=/inventory-service/**



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
