server:
  port: 8081
  servlet:
    context-path: /product_service

  spring:
    application:
      name: product_service

  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/


